import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const foodMenu: Food[] = [
 {
    id:'1',
    name: 'Masala Dosa',
    price: 100,
    cookTime: '10-20',
    favorite: true,
    origins: ['south India'],
    stars: 3.5,
    imageUrl: 'assets/food-4.jpg',
  },
   {
    id:'5',
    name: 'Chicken Fried Rice',
    price: 95,
    cookTime: '20-30',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 4.5,
    imageUrl: 'assets/food-5.jpg',
  },
  {
    id:'3',
    name: 'Butter Naan',
    price: 160,
    cookTime: '10-15',
    favorite: true,
    origins: ['india', 'middle east', 'china'],
    stars: 4.2,
    imageUrl: 'assets/food-2.jpg',
  },
   
   {
    id:'4',
    name: 'Chicken Biryani ',
    cookTime: '10-20',
    price: 250,
    favorite: false,
    origins: ['Indian', 'Persian'],
    stars: 5,
    imageUrl: 'assets/food-1.jpg',
  },
  {
    id:'5',
    name: 'Idly',
    price: 125,
    cookTime: '10-15',
    favorite: false,
    origins: ['Indian','South Indian'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
  },
 
 
  {
    id:'6',
    name: 'Chole Bhature',
    price: 150,
    cookTime: '30-40',
    favorite: false,
    origins: ['italy'],
    stars: 4.1,
    imageUrl: 'assets/food-6.jpg',
  },
  {
    id:'7',
    name: 'Chicken Curry Rice',
    price: 180,
    cookTime: '20-25',
    favorite: true,
    origins: ['Indian'],
    stars: 4.4,
    imageUrl: 'assets/food-7.jpg',
  },
   {
    id:'8',
    name: 'Crispy Chilli Garlic Baby Corn',
    price: 240,
    cookTime: '25-30',
    favorite: false,
    origins: ['Indian', 'Asia'],
    stars: 4.2,
    imageUrl: 'assets/food-8.jpg',
  },
   {
    id:'9',
    name: 'Noodles',
    price: 170,
    cookTime: '15-20',
    favorite: false,
    origins: ['china'],
    stars: 4,
    imageUrl: 'assets/food-9.jpg',

  },
   {
    id:'9',
    name: 'Chicken 65',
    price: 260,
    cookTime: '25-30',
    favorite: true,
    origins: ['india', 'Asia'],
    stars: 5,
    imageUrl: 'assets/food-10.jpg',
  },
]